/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/volatility/smilesection.hpp>
#include <ql/termstructures/volatility/volatilitytype.hpp>
#include <ql/termstructures/volatility/flatsmilesection.hpp>

#include <ql/termstructures/volatility/equityfx/all.hpp>
#include <ql/termstructures/volatility/capfloor/all.hpp>
#include <ql/termstructures/volatility/inflation/all.hpp>
#include <ql/termstructures/volatility/optionlet/all.hpp>
#include <ql/termstructures/volatility/swaption/all.hpp>
