/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/indexes/ibor/euribor.hpp>
#include <ql/indexes/ibor/libor.hpp>
#include <ql/indexes/ibor/usdlibor.hpp>

